spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groupaybe_demo
    username: root
    password: admin09
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
